export default [
  {
    key: '1',
    name: 'Mike',
    age: 32,
    address: '10 Downing Street',
    status: true,
    gender: 'male',
    birthday: '1990-04-13',
    color: 'red',
    country: 'col',
  },
  {
    key: '2',
    name: 'Daniel',
    age: 12,
    address: '14 Downing Street',
    status: false,
    gender: 'female',
    birthday: '1990-04-14',
    color: 'green',
    country: 'col',
  },
  {
    key: '3',
    name: 'John',
    age: 42,
    address: '10 Downing Street',
    status: true,
    gender: 'male',
    birthday: '1990-04-15',
    color: 'black',
    country: 'arg',
  },
];
